name: Set PR Labels

on:
  pull_request:
    types: opened
jobs:
  SetLabels:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set Labels
        uses: woocommerce/grow/branch-label@actions-v1
