name: Set PR Labels

on:
  pull_request:
    types: opened
jobs:
  SetLabels:
    runs-on: ubuntu-latest
    steps:
      - name: Set Labels
        uses: woocommerce/grow/branch-label@f1a6c217ba3b49c18029ebe7761f7be4abe992d7 # actions-v1
