name: Build and Upload zip

on: workflow_call
jobs:
  build_project:
        name: Build and upload
        runs-on: ubuntu-latest

        steps:

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup node version
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'

            - name: Restore node_modules
              id: cache-node-modules
              uses: actions/cache@v4
              env:
                  cache-name: cache-node-modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

            - name: Install WP-CLI
              run: |
                  mkdir tools
                  wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -P ${PWD}/tools/
                  chmod +x tools/wp-cli.phar && mv tools/wp-cli.phar tools/wp

            - name: Rebuild node-sass
              run: npm rebuild node-sass

            - name: Build
              run: |
                  export PATH=$PATH:${PWD}/tools
                  npm run build:zip

            - name: Upload zip
              uses: actions/upload-artifact@v4
              with:
                name: pinterest-for-woocommerce
                path: ${{ github.workspace }}/pinterest-for-woocommerce.zip
 
