name: QIT - Cron CI

on:
    schedule:
        # Run at 04:00 on Tuesdays.
        - cron: '0 4 * * 2'

jobs:

    setup:
        name: Setup environments
        uses: ./.github/workflows/setup-env.yml

    build_project:
        name: Package
        needs: setup
        uses: ./.github/workflows/build-upload-zip.yml

    qit-tests:
        name: QIT
        needs: build_project
        uses: ./.github/workflows/run-qit.yml
        secrets: inherit
        with:
          extension: 'pinterest-for-woocommerce'
          artifact: 'pinterest-for-woocommerce'
          wp-version: 'nightly'
          wc-version: 'nightly'
          test-activation: true
          test-security: true
          test-phpcompatibility: true
          test-validation: true
          test-phpstan: false # TODO: Enable this once the PHPStan tests are fixed
          test-woo-api: true
          test-woo-e2e: true
          test-malware: true

    handle-success:
        if: ${{ success() }}
        needs: qit-tests
        name: Handle success
        runs-on: ubuntu-latest
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        steps:
            - uses: act10ns/slack@v2
              with:
                  status: success
                  message: "Scheduled workflow <{{workflowUrl}}|{{workflow}}> with run ID <{{workflowRunUrl}}|{{runId}}> passed."

    handle-error:
      if: ${{ failure() }}
      needs: qit-tests
      name: Handle failure
      runs-on: ubuntu-latest
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      steps:
          - uses: act10ns/slack@v2
            with:
                status: failure
                message: "Scheduled workflow <{{workflowUrl}}|{{workflow}}> with run ID <{{workflowRunUrl}}|{{runId}}> failed. You can find the results in the artifacts section."
