name: QIT - Merge to Trunk CI

on:
  pull_request:
    branches:
      - trunk
    types:
      - closed

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
    setup:
        if: github.event.pull_request.merged == true
        name: Setup environments
        uses: ./.github/workflows/setup-env.yml

    build_project:
        needs: setup
        name: Package
        uses: ./.github/workflows/build-upload-zip.yml

    qit-tests:
        if: github.event.pull_request.merged == true
        name: QIT tests
        needs: build_project
        uses: ./.github/workflows/run-qit.yml
        secrets: inherit
        with:
          extension: 'pinterest-for-woocommerce'
          artifact: 'pinterest-for-woocommerce'
          test-activation: true
          test-security: true
          test-phpcompatibility: true
          test-validation: true
          test-phpstan: false # TODO: Enable this once the PHPStan tests are fixed

    handle-success:
        if: ${{ success() }}
        needs: qit-tests
        name: Handle success
        runs-on: ubuntu-latest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        steps:
          - uses: act10ns/slack@44541246747a30eb3102d87f7a4cc5471b0ffb7d #v2.1.0
            with:
                status: success
                message: "Workflow <{{workflowUrl}}|{{workflow}}> with run ID <{{workflowRunUrl}}|{{runId}}> in PR <{{refUrl}}|{{ref}}> passed."

    handle-cancelled:
        if: ${{ cancelled() }}
        needs: qit-tests
        name: Handle cancellation
        runs-on: ubuntu-latest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        steps:
          - uses: act10ns/slack@44541246747a30eb3102d87f7a4cc5471b0ffb7d #v2.1.0
            with:
                status: cancelled
                message: "Workflow <{{workflowUrl}}|{{workflow}}> with run ID <{{workflowRunUrl}}|{{runId}}> in PR <{{refUrl}}|{{ref}}> cancelled."

    handle-error:
        if: ${{ failure() }}
        needs: qit-tests
        name: Handle failure
        runs-on: ubuntu-latest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        steps:
          - uses: act10ns/slack@44541246747a30eb3102d87f7a4cc5471b0ffb7d #v2.1.0
            with:
                status: failure
                message: "Workflow <{{workflowUrl}}|{{workflow}}> with run ID <{{workflowRunUrl}}|{{runId}}> in PR <{{refUrl}}|{{ref}}> failed."

