name: PHP Unit Tests

on:
  push:
    branches:
      - trunk
      - develop
    paths:
      - "**.php"
      - composer.json
      - composer.lock
      - .github/workflows/php-unit-tests.yml
      - bin/install-wp-tests.sh
  pull_request:
    paths:
      - "**.php"
      - composer.json
      - composer.lock
      - .github/workflows/php-unit-tests.yml
      - bin/install-wp-tests.sh

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  UnitTests:
    name: PHP unit tests - PHP ${{ matrix.php }}, WP ${{ matrix.wp-version }}, WC ${{ matrix.wc-version }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      WP_CORE_DIR: "/tmp/wordpress/src"
      WP_TESTS_DIR: "/tmp/wordpress/tests/phpunit"
    strategy:
      matrix:
        php: [7.4, 8.3]
        wp-version: [latest]
        wc-version: [latest]
        include:
          - php: 7.4
            wp-version: '6.9.0'
            wc-version: '10.9.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Prepare PHP
        uses: woocommerce/grow/prepare-php@b9c1e59aae9fdbe668b068ebd59c1545a88ea9fa # actions-v3.0.5
        with:
          php-version: "${{ matrix.php }}"

      - name: Prepare MySQL
        uses: woocommerce/grow/prepare-mysql@f1a6c217ba3b49c18029ebe7761f7be4abe992d7 # actions-v1

      - name: Install WP tests
        shell: bash
        env:
          WP_VERSION: ${{ matrix.wp-version }}
          WC_VERSION: ${{ matrix.wc-version }}
        run: ./bin/install-wp-tests.sh wordpress_test root root localhost "$WP_VERSION"

      - name: Run PHP unit tests
        run: composer test-unit
